### ISSUE TITLE
Параметр распределения p

### ISSUE THREAD

**Issue by ndavnvl** [pycpp2019/2.2.2_MonteCarlo#1]
Полагаю параметр **p** = **π** / 4

**Comment by agerasev** [comment]
Да, всё верно, я задание переписал не глядя. Спасибо за замечание!

**Comment by agerasev** [comment]
Исправил описание: https://github.com/pycpp2019/2.2.2_MonteCarlo/commit/65844488beaae2c1b6dfc8937bfe0cfd2f1c2fd5
